GET http://localhost:3001/api/poetryArray
###
POST http://localhost:3001/api/poetryArray 
Content-Type: application/json

{
    "title": "Revolucionaria!!",
    "content": ["Latidos que borran fronteras.", 
    "Mirada que refleja libertad.",
    "Su piel como color de mi bandera", 
    "y su voz como mi himno nacional.",
    "/br",
    "Pasos que dejan grandes huellas,",
    "manos que albergan en un amplio hogar",
    "y en su espalda residen las estrellas",
    "que mis yemas ansían tanto conquistar.",
    "/br",
    "Su regazo regala una enorme trinchera",
    "que me reguarda de todo mal",
    "y en sus abrazos encuentro la tregua",
    "frente a cualquier pensamiento radical.",
    "/br",
    "En sus ojos, eterno esbozo de sinceridad.",
    "Contra ella perdería toda guerra,",
    "pues a su vera obtengo la mayor paz",
    "que se pueda sentir sobre La Tierra."]
}