GET http://localhost:3001/api/poetryArray
###
POST http://localhost:3001/api/poetryArray 
Content-Type: application/json

{
    "title": "Amistad",
    "content": ["Qué bonito e inequívoco", 
    "es el valor de lo recíproco.",
    "Formar lazos, crear vínculos", 
    "regalar abrazos, cerrar círculos.",
    "/br",
    "Y qué gran error sacrificar a tus pilares",
    "con el fin de alcanzar la gloria,",
    "pues dime tú de que valen los diamantes",
    "si celebras tu solo la victoria.",
    "/br",
    "Me siento como un pirata",
    "sobre un barco sin capitanes",
    "donde remamos todos juntos",
    "sin brújulas ni mapas,",
    "/br",
    "trazando nuevos planes,",
    "conquistando el mundo,",
    "vagando sin rumbo",
    "por exóticos lugares.",
    "/br",
    "bebiendo ron y vino,",
    "y bañándonos en oro.",
    "porque quien tiene un amigo...",
    "           tiene un tesoro."]
}